services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://hcwuser:hcwpasswd@db:5432/hcw?schema=public
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "3000:3000"  
      - "5555:5555"

  patient:
    build:
      context: patient
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    depends_on:
      - backend
    restart: always

  admin:
    build:
      context: admin
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

  practitioner:
    build:
      context: practitioner
      dockerfile: Dockerfile
    ports:
      - "4202:80"
    depends_on:
      - backend
    restart: always

  db:
    image: docker.io/postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: hcwuser
      POSTGRES_PASSWORD: hcwpasswd
      POSTGRES_DB: hcw
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data:
